# Generated by Django 3.1 on 2020-09-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='date_posted',
            field=models.DateField(),
        ),
    ]
