# Generated by Django 3.1.1 on 2020-09-15 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('Art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.art')),
            ],
        ),
    ]
