# Generated by Django 3.1.1 on 2020-09-15 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200915_1823'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
